services:
  - type: worker
    name: mc-bedrock
    env: docker
    dockerfilePath: ./Dockerfile
    plan: scale
    disk:
      name: bedrock-world
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: EULA
        value: "TRUE"
      - key: VERSION
        value: "LATEST"          # <- YAHI CHANGE KARO – "1.21.3" nahi
      - key: VIEW_DISTANCE
        value: "16"
      - key: MEMORY
        value: "4G"
