services:
  - type: worker
    name: mc-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: scale
    disk:
      name: mc-world
      mountPath: /data          # IMPORTANT: image uses /data for world
      sizeGB: 10
    envVars:
      - key: EULA
        value: "TRUE"
      - key: VERSION
        value: "1.21.3"         # ya "LATEST"
      - key: VIEW_DISTANCE
        value: "16"
      - key: SIMULATION_DISTANCE
        value: "10"
      - key: MEMORY
        value: "4G"
      - key: ENABLE_WHITELIST
        value: "false"          # tu chahe toh "true" kar de
